spring.application.name=telegram_bot

telegram.bot.username=${TELEGRAM_BOT_USERNAME}
telegram.bot.token=${TELEGRAM_BOT_TOKEN}

#open router api key
openrouter.api.key=${OPENROUTER_API_KEY}


spring.data.mongodb.uri=${MONGODB_URI}

#logging.level.org.springframework.data.mongodb=DEBUG
#logging.level.org.mongodb.driver=DEBUG
